### ISSUE TITLE
Why jax?

### ISSUE THREAD

**Issue by Franklin-Yao** [vballoli/vit-flax#1]
Will it be much faster than Pytorch?

**Comment by vballoli** [comment]
Hi, you can read up on how JAX is useful [here](https://github.com/google/jax#what-is-jax). Speedup is hard to measure since various reports on different hardware report different metrics, but I believe this code can be useful to cases that require and/or use numpy, JIT, XLA, TPU support, etc.

Feel free to reopen this if you want to continue the thread as a discussion.
